_wandb:
    value:
        cli_version: 0.24.2
        e:
            hmdi780idkbwt2fmkcofv8poswtb7snt:
                args:
                    - --dataset
                    - data/mcq_event_timeline_strong.jsonl
                    - --audio-root
                    - data/audio
                    - --audioflamingo-repo
                    - external/audio-flamingo
                    - --model-base
                    - nvidia/audio-flamingo-3
                    - --num-gpus
                    - "1"
                    - --batch-size
                    - "2"
                    - --max-new-tokens
                    - "16"
                    - --limit
                    - "100"
                    - --results-root
                    - results
                    - --wandb
                    - --wandb-project
                    - tacobelal
                    - --wandb-log-every
                    - "50"
                codePath: src/utils/evaluate_mcq_order_audioflamingo.py
                codePathLocal: src/utils/evaluate_mcq_order_audioflamingo.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "12.3"
                disk:
                    /:
                        total: "1889035878400"
                        used: "666711883776"
                email: younisskandah@gmail.com
                executable: /home/fs73062/younissk01/TACoBeLAL/.venv/bin/python3
                git:
                    commit: e92529f8cd49ab235822bd3b09dc7abc05ddbd0f
                    remote: https://github.com/younissk/TACoBeLAL.git
                gpu: NVIDIA A40
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-21a6623a-50e3-e74e-179f-2de1d617fd08
                host: n3067-001
                memory:
                    total: "270306295808"
                os: Linux-4.18.0-477.10.1.el8_8.x86_64-x86_64-with-glibc2.28
                program: /home/fs73062/younissk01/TACoBeLAL/src/utils/evaluate_mcq_order_audioflamingo.py
                python: CPython 3.13.12
                root: /home/fs73062/younissk01/TACoBeLAL
                slurm:
                    cluster_name: vsc5
                    conf: /var/spool/slurm/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "16"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: p73062
                    job_cpus_per_node: "16"
                    job_gid: "73062"
                    job_gpus: "1"
                    job_id: "7229171"
                    job_name: mcq-order-af3
                    job_nodelist: n3067-001
                    job_num_nodes: "1"
                    job_partition: zen2_0256_a40x2
                    job_qos: 33 x a40 nodes with 32 cores each
                    job_uid: "78098"
                    job_user: younissk01
                    jobid: "7229171"
                    localid: "0"
                    mem_per_node: "125000"
                    nnodes: "1"
                    node_aliases: (null)
                    nodeid: "0"
                    nodelist: n3067-001
                    nprocs: "8"
                    ntasks: "8"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /home/fs73062/younissk01/TACoBeLAL
                    submit_host: l50.vsc.xcat
                    task_pid: "2763160"
                    tasks_per_node: "8"
                    topology_addr: n3067-001
                    topology_addr_pattern: node
                    working_cluster: vsc5:slurm5ctld.vsc5.prov:7817:9728:109
                startedAt: "2026-02-10T10:18:57.437148Z"
                writerId: hmdi780idkbwt2fmkcofv8poswtb7snt
        m: []
        python_version: 3.13.12
        t:
            "1":
                - 105
            "2":
                - 105
            "3":
                - 2
                - 15
                - 16
            "4": 3.13.12
            "5": 0.24.2
            "12": 0.24.2
            "13": linux-x86_64
audio_root:
    value: data/audio
audioflamingo_repo:
    value: external/audio-flamingo
batch_size:
    value: 2
dataset:
    value: data/mcq_event_timeline_strong.jsonl
limit:
    value: 100
max_new_tokens:
    value: 16
model_base:
    value: nvidia/audio-flamingo-3
num_gpus:
    value: 1
task_id:
    value: MCQ-ORDER
think_mode:
    value: false
